### ISSUE TITLE
`repository` is expected to be an object

### ISSUE THREAD

**Issue by zeke** [ungoldman/gh-release#47]
It's valid to have string value for repository, but `gh-release` currently expects it to be an object with a `url` property:

```
> gh-release --draft --assets out/wifi-tracker-darwin-x64/wifi-tracker-darwin-x64.zip

Your GitHub username: zeke
Your GitHub password: ✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔✔

Your GitHub OTP/2FA Code (optional): 462508

/Users/zeke/zeke/wifi-tracker/node_modules/gh-release/bin/lib/get-defaults.js:13
  var repoPath = pkg.repository.url.split('github.com')[1].slice(1).split('/')
                                   ^

TypeError: Cannot read property 'split' of undefined
    at getDefaults (/Users/zeke/zeke/wifi-tracker/node_modules/gh-release/bin/lib/get-defaults.js:13:36)
    at /Users/zeke/zeke/wifi-tracker/node_modules/gh-release/bin/cli.js:47:3
    at afterWrite (/Users/zeke/zeke/wifi-tracker/node_modules/gh-release/node_modules/ghauth/ghauth.js:169:9)
    at FSReqWrap.oncomplete (fs.js:111:15)
```

```
❯ cat package.json | json repository
https://github.com/zeke/wifi-tracker
```

I can work on a PR for this.

**Comment by ungoldman** [comment]
Good point @zeke, thanks! Would love a PR if you have time!

**Comment by ungoldman** [comment]
Released in [v2.2.1](https://github.com/ungoldman/gh-release/releases/tag/v2.2.1), thanks so much for your help @zeke!

**Comment by zeke** [comment]
🍕

**Comment by zeke** [comment]
Thanks for the quick turnaround.

**Comment by zeke** [comment]
Yay it works.

https://github.com/zeke/wifi-tracker/releases

Warning: This app sucks. Don't download it yet! :)
